# Configuración para Supabase
project_id = "hrwfcfjysojhpcdlxamq"

[api]
enabled = true
port = 54321
schemas = ["public", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:5500"
additional_redirect_urls = ["https://localhost:5500"]
jwt_expiry = 3600
enable_signup = true

[database]
enabled = true
port = 54322

[storage]
enabled = true
port = 54323
file_size_limit = "50MiB"

[edge_functions]
enabled = true
port = 54324

[studio]
enabled = true
port = 54323
